name: Deploy Laravel EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar chave SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Adicionar host à lista de conhecidos
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 3.20.235.172 >> ~/.ssh/known_hosts

      - name: Deploy para EC2
        run: |
          ssh ec2-user@3.20.235.172 "
            cd /home/ec2-user/alpes-api &&
            git reset --hard &&
            git pull origin master &&
            composer install --no-dev --optimize-autoloader &&
            php artisan migrate --force &&
            php artisan config:cache &&
            sudo systemctl restart php-fpm nginx
          "
